In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

In [2]:
events = pd.read_csv('Event ID and Titles.csv', encoding="Latin1")
Ratings = pd.read_csv('User_Ratings_Converted (1).csv', encoding="Latin1")

Mean = Ratings.groupby(by="User_ID", as_index = False)['User Rating'].mean()
Rating_avg = pd.merge(Ratings, Mean, on = "User_ID")
Rating_avg['adg_rating']=Rating_avg['User Rating_x']-Rating_avg['User Rating_y']
Rating_avg.head()

,Unnamed: 0,User_ID,EventID,User Rating_x,Activity Type/Genre,User Rating_y,adg_rating
0,0,User_ID1,93fbdb91dbbb241c706203da7fa4c08b,1,"Concert, Concert Band",3.4,-2.4
1,1,User_ID1,f798cf945df3c3fd2d8fc1df821e8c1a,5,"Literature, Lectures, Comedy, Poetry",3.4,1.6
2,2,User_ID1,c1bc4f9ea142caddf3ecc7c94141f929,1,"Concert, Concert Band",3.4,-2.4
3,3,User_ID1,ee67507c5df71fd885d5e119391295d7,1,"Rock and Roll, Blues, Pop, Jazz, Music Festival",3.4,-2.4
4,4,User_ID1,2122b8a4800410b30d6b374c92ffe63d,5,"Opera, Musicals, Broadway",3.4,1.6

In [3]:
check = pd.pivot_table(Rating_avg,values='User Rating_x',index='User_ID',columns='EventID')
check.head()

EventID,0137b8241bf0f35dae5d0b71cb23bc95,017e6e5a2c96deb69d63cbc11dab5795,08e7241e2e0b7c8f320cf6ff0d0d1a87,08eb65fc32f982ab8666c0a31541a57b,0b148b1104c3030f172a35f8c253e520,0f9881e3af45f7426df1adfbc18d1e4b,137948d7a8e312a01c306829244dd104,16bcf64327887a4b0fdfead1299c5830,2122b8a4800410b30d6b374c92ffe63d,2905612047b8f3941191f995e45f7610,...,e32a42e4a857d67720020c793f5afd2a,e974e7bfa3510dfc3f52648675c62dbc,ea959c875274584640c0aa4a66d350c0,eb429ee495a1c2c63e9e5db2743d5b7b,ecf5694c3f4ef47ce2447e338222266b,ee67507c5df71fd885d5e119391295d7,f007f18a404660855aa55b50e984d1b8,f798cf945df3c3fd2d8fc1df821e8c1a,fd33b0be7e67ce5b4fcfe08df71ba78d,fea5355d669eaeb655610755fe1c0c0e
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,5.0,NaN,NaN
User_ID10,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
User_ID100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,1.0,3.0,NaN,NaN
User_ID101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
User_ID102,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN,NaN

In [4]:
final = pd.pivot_table(Rating_avg,values='adg_rating',index='User_ID',columns='EventID')
final.head()

EventID,0137b8241bf0f35dae5d0b71cb23bc95,017e6e5a2c96deb69d63cbc11dab5795,08e7241e2e0b7c8f320cf6ff0d0d1a87,08eb65fc32f982ab8666c0a31541a57b,0b148b1104c3030f172a35f8c253e520,0f9881e3af45f7426df1adfbc18d1e4b,137948d7a8e312a01c306829244dd104,16bcf64327887a4b0fdfead1299c5830,2122b8a4800410b30d6b374c92ffe63d,2905612047b8f3941191f995e45f7610,...,e32a42e4a857d67720020c793f5afd2a,e974e7bfa3510dfc3f52648675c62dbc,ea959c875274584640c0aa4a66d350c0,eb429ee495a1c2c63e9e5db2743d5b7b,ecf5694c3f4ef47ce2447e338222266b,ee67507c5df71fd885d5e119391295d7,f007f18a404660855aa55b50e984d1b8,f798cf945df3c3fd2d8fc1df821e8c1a,fd33b0be7e67ce5b4fcfe08df71ba78d,fea5355d669eaeb655610755fe1c0c0e
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6,NaN,...,NaN,NaN,NaN,NaN,NaN,-2.4,-2.4,1.6,NaN,NaN
User_ID10,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,NaN
User_ID100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,...,NaN,NaN,-1.0,NaN,NaN,NaN,-1.0,1.0,NaN,NaN
User_ID101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
User_ID102,NaN,NaN,NaN,NaN,NaN,NaN,1.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.4,-0.6,NaN,NaN

In [5]:
final_event = final.fillna(final.mean(axis=0))
final_event.head()

EventID,0137b8241bf0f35dae5d0b71cb23bc95,017e6e5a2c96deb69d63cbc11dab5795,08e7241e2e0b7c8f320cf6ff0d0d1a87,08eb65fc32f982ab8666c0a31541a57b,0b148b1104c3030f172a35f8c253e520,0f9881e3af45f7426df1adfbc18d1e4b,137948d7a8e312a01c306829244dd104,16bcf64327887a4b0fdfead1299c5830,2122b8a4800410b30d6b374c92ffe63d,2905612047b8f3941191f995e45f7610,...,e32a42e4a857d67720020c793f5afd2a,e974e7bfa3510dfc3f52648675c62dbc,ea959c875274584640c0aa4a66d350c0,eb429ee495a1c2c63e9e5db2743d5b7b,ecf5694c3f4ef47ce2447e338222266b,ee67507c5df71fd885d5e119391295d7,f007f18a404660855aa55b50e984d1b8,f798cf945df3c3fd2d8fc1df821e8c1a,fd33b0be7e67ce5b4fcfe08df71ba78d,fea5355d669eaeb655610755fe1c0c0e
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,0.316129,0.09589,-0.003448,-0.408955,-1.0,-0.555556,-0.463158,0.028814,1.600000,0.133333,...,-0.093023,-0.086667,-0.028718,-0.046154,0.066667,-2.400000,-2.40000,1.600000,0.262602,0.5
User_ID10,0.316129,0.09589,-0.003448,1.000000,-1.0,-0.555556,-0.463158,0.028814,-0.159091,0.133333,...,-0.093023,-0.086667,-0.028718,-0.046154,0.066667,-0.275862,-1.00000,-0.215652,0.262602,0.5
User_ID100,0.316129,0.09589,-0.003448,-0.408955,-1.0,-0.555556,-0.463158,-1.000000,-0.159091,0.133333,...,-0.093023,-0.086667,-1.000000,-0.046154,0.066667,-0.275862,-1.00000,1.000000,0.262602,0.5
User_ID101,0.316129,0.09589,-0.003448,-0.408955,-1.0,-0.555556,-0.463158,0.028814,-0.159091,0.133333,...,-0.093023,-0.086667,-0.028718,-0.046154,0.066667,-0.275862,-0.04845,-0.215652,0.262602,0.5
User_ID102,0.316129,0.09589,-0.003448,-0.408955,-1.0,-0.555556,1.400000,0.028814,-0.159091,0.133333,...,-0.093023,-0.086667,-0.028718,-0.046154,0.066667,-0.275862,1.40000,-0.600000,0.262602,0.5

In [6]:
# Replacing NaN by user Average
final_user = final.apply(lambda row: row.fillna(row.mean()), axis=1)
final_user.head()

EventID,0137b8241bf0f35dae5d0b71cb23bc95,017e6e5a2c96deb69d63cbc11dab5795,08e7241e2e0b7c8f320cf6ff0d0d1a87,08eb65fc32f982ab8666c0a31541a57b,0b148b1104c3030f172a35f8c253e520,0f9881e3af45f7426df1adfbc18d1e4b,137948d7a8e312a01c306829244dd104,16bcf64327887a4b0fdfead1299c5830,2122b8a4800410b30d6b374c92ffe63d,2905612047b8f3941191f995e45f7610,...,e32a42e4a857d67720020c793f5afd2a,e974e7bfa3510dfc3f52648675c62dbc,ea959c875274584640c0aa4a66d350c0,eb429ee495a1c2c63e9e5db2743d5b7b,ecf5694c3f4ef47ce2447e338222266b,ee67507c5df71fd885d5e119391295d7,f007f18a404660855aa55b50e984d1b8,f798cf945df3c3fd2d8fc1df821e8c1a,fd33b0be7e67ce5b4fcfe08df71ba78d,fea5355d669eaeb655610755fe1c0c0e
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.600000,1.332268e-16,...,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,1.332268e-16,-2.400000,-2.400000,1.600000,1.332268e-16,1.332268e-16
User_ID10,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,-1.000000,0.000000,0.000000e+00,0.000000e+00
User_ID100,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000,-1.000000,1.000000,0.000000e+00,0.000000e+00
User_ID101,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,0.022222,2.222222e-02,...,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,2.222222e-02,0.022222,0.022222,0.022222,2.222222e-02,2.222222e-02
User_ID102,6.666667e-02,6.666667e-02,6.666667e-02,6.666667e-02,6.666667e-02,6.666667e-02,1.400000e+00,6.666667e-02,0.066667,6.666667e-02,...,6.666667e-02,6.666667e-02,6.666667e-02,6.666667e-02,6.666667e-02,0.066667,1.400000,-0.600000,6.666667e-02,6.666667e-02

In [7]:
# user similarity on replacing NAN by item(movie) avg
cosine = cosine_similarity(final_event)
np.fill_diagonal(cosine, 0 )
similarity_with_event =pd.DataFrame(cosine,index=final_event.index)
similarity_with_event.columns=final_user.index
similarity_with_event.head()

User_ID,User_ID1,User_ID10,User_ID100,User_ID101,User_ID102,User_ID103,User_ID104,User_ID105,User_ID106,User_ID107,...,User_ID90,User_ID91,User_ID92,User_ID93,User_ID94,User_ID95,User_ID96,User_ID97,User_ID98,User_ID99
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,0.000000,0.339985,0.540416,0.213309,0.140021,0.109095,0.009279,0.318600,0.172783,0.369736,...,0.304192,0.543658,0.340562,0.235439,0.281878,0.228178,0.264233,0.509323,0.149285,0.153358
User_ID10,0.339985,0.000000,0.438289,0.166352,0.239749,0.194958,0.174009,0.374045,0.126577,0.299845,...,0.125974,0.449173,0.338114,0.265243,0.062605,0.342125,0.453017,0.424156,0.245062,0.077342
User_ID100,0.540416,0.438289,0.000000,0.364153,0.340949,0.255203,0.276874,0.403983,0.394432,0.558660,...,0.289394,0.535547,0.590346,0.432075,0.296382,0.357496,0.400286,0.558236,0.378589,0.342741
User_ID101,0.213309,0.166352,0.364153,0.000000,0.258421,0.218722,0.436495,0.362520,0.280693,0.334264,...,0.160259,0.304950,0.399584,0.349755,0.259124,0.326940,0.188230,0.075882,0.270884,0.621132
User_ID102,0.140021,0.239749,0.340949,0.258421,0.000000,0.129853,0.222185,0.270006,0.299639,0.276795,...,0.397000,0.315031,0.522295,0.328579,0.303352,0.161484,0.124443,0.210243,0.359361,0.416993

In [8]:
def find_n_neighbours(df,n):
    order = np.argsort(df.values, axis=1)[:, :n]
    df = df.apply(lambda x: pd.Series(x.sort_values(ascending=False)
           .iloc[:n].index, 
          index=['top{}'.format(i) for i in range(1, n+1)]), axis=1)
    return df

In [9]:
# top 30 neighbours for each user
sim_user_30_e = find_n_neighbours(similarity_with_event,30)
sim_user_30_e.head()

,top1,top2,top3,top4,top5,top6,top7,top8,top9,top10,...,top21,top22,top23,top24,top25,top26,top27,top28,top29,top30
User_ID,,,,,,,,,,,,,,,,,,,,,
User_ID1,User_ID23,User_ID91,User_ID100,User_ID457,User_ID132,User_ID459,User_ID35,User_ID164,User_ID4,User_ID97,...,User_ID110,User_ID340,User_ID287,User_ID240,User_ID445,User_ID456,User_ID291,User_ID249,User_ID329,User_ID57
User_ID10,User_ID220,User_ID301,User_ID343,User_ID52,User_ID297,User_ID23,User_ID254,User_ID81,User_ID124,User_ID296,...,User_ID244,User_ID202,User_ID27,User_ID168,User_ID180,User_ID214,User_ID229,User_ID12,User_ID330,User_ID276
User_ID100,User_ID297,User_ID23,User_ID229,User_ID6,User_ID171,User_ID489,User_ID339,User_ID276,User_ID217,User_ID412,...,User_ID35,User_ID57,User_ID92,User_ID279,User_ID256,User_ID156,User_ID176,User_ID456,User_ID219,User_ID291
User_ID101,User_ID99,User_ID62,User_ID458,User_ID3,User_ID122,User_ID243,User_ID319,User_ID339,User_ID109,User_ID50,...,User_ID20,User_ID195,User_ID267,User_ID146,User_ID240,User_ID308,User_ID297,User_ID227,User_ID456,User_ID414
User_ID102,User_ID194,User_ID230,User_ID297,User_ID234,User_ID39,User_ID415,User_ID493,User_ID68,User_ID153,User_ID92,...,User_ID360,User_ID208,User_ID181,User_ID382,User_ID327,User_ID140,User_ID383,User_ID475,User_ID452,User_ID137

In [29]:
def get_user_similar_events( user1, user2 ):
    common_events = Rating_avg[Rating_avg.User_ID == user1].merge(
    Rating_avg[Rating_avg.User_ID == user2],
    on = "EventID",
    how = "inner" )
    return common_events.merge( events, on ='EventID')

In [36]:
a = get_user_similar_events('User_ID10','User_ID220')
a = a.reindex(columns= ['User Rating_x_x','User Rating_x_y','Name'])
a.head()

,User Rating_x_x,User Rating_x_y,Name
0,5,5,A Tribute to The King: Taylor Rodriguez
1,3,3,Revolution: The Music of the Beatles a Symphon...
2,3,1,Revolution: The Music of the Beatles a Symphon...
3,3,3,Alive at the Bass
4,1,1,Berlioz Romeo and Juliet

In [13]:
Rating_avg = Rating_avg.astype({"EventID": str})
Movie_user = Rating_avg.groupby(by = 'User_ID')['EventID'].apply(lambda x:','.join(x))

In [26]:
def User_item_score1(user):
    Movie_seen_by_user = check.columns[check[check.index==user].notna().any()].tolist()
    a = sim_user_30_e[sim_user_30_e.index==user].values
    b = a.squeeze().tolist()
    d = Movie_user[Movie_user.index.isin(b)]
    l = ','.join(d.values)
    Movie_seen_by_similar_users = l.split(',')
    Movies_under_consideration = list(set(Movie_seen_by_similar_users)-set(list(map(str, Movie_seen_by_user))))
    Movies_under_consideration = list(map(str, Movies_under_consideration))
    score = []
    for item in Movies_under_consideration:
        c = final_event.loc[:,item]
        d = c[c.index.isin(b)]
        f = d[d.notnull()]
        avg_user = Mean.loc[Mean['User_ID'] == user,'User Rating'].values[0]
        index = f.index.values.squeeze().tolist()
        corr = similarity_with_event.loc[user,index]
        fin = pd.concat([f, corr], axis=1)
        fin.columns = ['adg_score','correlation']
        fin['score']=fin.apply(lambda x:x['adg_score'] * x['correlation'],axis=1)
        nume = fin['score'].sum()
        deno = fin['correlation'].sum()
        final_score = avg_user + (nume/deno)
        score.append(final_score)
    data = pd.DataFrame({'EventID':Movies_under_consideration,'score':score})
    top_5_recommendation = data.sort_values(by='score',ascending=False).head(5)
    Movie_Name = top_5_recommendation.merge(events, how='inner', on='EventID')
    Movie_Names = Movie_Name.Name.values.tolist()
    return Movie_Names

In [28]:
user = input("Enter the user id to whom you want to recommend : ")
predicted_movies = User_item_score1(user)
print(" ")
print("The Recommendations for User Id : " + user)
print("   ")
for i in predicted_movies:
    print(i)

Enter the user id to whom you want to recommend : User_ID101

The Recommendations for User Id : User_ID101

Performance and Artist Talk with Sean Miller
James McBride
Katherine Schwarzenegger Pratt
FOCUS: Marina Adams
Late Night Film: American Animals